### PR TITLE
corrected OH general registration deadline

### PR DESCRIPTION
**Pull request by hodgesmr**
From the [Ohio Secretary of State](https://olvr.sos.state.oh.us/):

>October 9, 2018 for the November 6, 2018 General Election

### CODE REVIEW

**Comment by hodgesmr** [comment]
Interestingly, the page gives conflicting information. It also say:

>You must register or update your voter registration no later than 30 days prior to an election.

Which would, in fact, be the original date of `2018-10-07`.

**Comment by hodgesmr** [comment]
I reached out to the Ohio Secretary of State Elections Devision for clarification. Will report back if I get a response.

**Comment by fpereyra** [comment]
@hodgesmr thank you!

**Comment by hodgesmr** [comment]
The Elections Division of the Ohio Secretary of State has responded to my inquiry and has clarified: **2018-10-09**.

screen shot 2018-01-29 at 9 03 53 am
 is the deadline to register to vote in Ohio for the 2018 midterms.

**Pull request merged**
